In [1]:
import numpy as np
#l = [1,2,3,4,5]

def vander_cal(ivector,n,increasing=False):
    if not increasing:
        out = np.array([x**(n-i-1) for x in ivector for i in range(n)]).reshape(ivector.size,n)
    else:
        out = np.array([x**i for x in ivector for i in range(n)]).reshape(ivector.size,n)
    return out
        

In [2]:
ivector = np.array([1,2,3,4,5])
ncol = 5
matrix_asc = vander_cal(ivector,ncol,True)
matrix_des = vander_cal(ivector,ncol,False)

In [60]:
print(matrix_asc)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [3]:
print(matrix_des)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
def movingAverage(inputValue, k):
  z = 1
  output = np.convolve(inputValue, np.ones(k), 'valid') / k
  return output

In [6]:
inputValue = np.array([10,20,30,40,50,60,70,80,90,100])
k = 4
out = movingAverage(inputValue, k).round()
print(out)

[25. 35. 45. 55. 65. 75. 85.]


In [7]:
 #Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
inputValue = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
out = movingAverage(inputValue, k).round()
print(out)

[  5.   5.   6.   7.  10.  29.  49.  73.  84.  93. 116.]
